# Generated by Django 5.0.6 on 2024-05-21 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='data',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid data format', regex='^[A-Za-z]{10}$')]),
            preserve_default=False,
        ),
    ]
