# Generated by Django 5.0.6 on 2024-05-21 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_alter_singer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='data',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid data format', regex='^[A-Z][a-z]*$|^[A-Z][A-Z]*$|^[a-z][a-z]*$')]),
        ),
    ]
