# Generated by Django 5.0.6 on 2024-06-18 10:23

import drf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_alter_singer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=drf.models.upload_to),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
